# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rotate.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rotate(object):
    def setupUi(self, rotate):
        rotate.setObjectName("rotate")
        rotate.resize(400, 300)
        self.aaa = QtWidgets.QDialogButtonBox(rotate)
        self.aaa.setGeometry(QtCore.QRect(-50, 230, 341, 32))
        self.aaa.setOrientation(QtCore.Qt.Horizontal)
        self.aaa.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aaa.setObjectName("aaa")
        self.label = QtWidgets.QLabel(rotate)
        self.label.setGeometry(QtCore.QRect(30, 112, 121, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(rotate)
        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(rotate)
        self.aaa.accepted.connect(rotate.accept)
        self.aaa.rejected.connect(rotate.reject)
        QtCore.QMetaObject.connectSlotsByName(rotate)

    def retranslateUi(self, rotate):
        _translate = QtCore.QCoreApplication.translate
        rotate.setWindowTitle(_translate("rotate", "Dialog"))
        self.label.setText(_translate("rotate", "请输入旋转角度："))
