# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scale.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scale(object):
    def setupUi(self, scale):
        scale.setObjectName("scale")
        scale.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(scale)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(scale)
        self.lineEdit.setGeometry(QtCore.QRect(170, 120, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(scale)
        self.label.setGeometry(QtCore.QRect(20, 120, 121, 20))
        self.label.setObjectName("label")

        self.retranslateUi(scale)
        self.buttonBox.accepted.connect(scale.accept)
        self.buttonBox.rejected.connect(scale.reject)
        QtCore.QMetaObject.connectSlotsByName(scale)

    def retranslateUi(self, scale):
        _translate = QtCore.QCoreApplication.translate
        scale.setWindowTitle(_translate("scale", "Dialog"))
        self.label.setText(_translate("scale", "请输入缩/放比例："))
