# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sp(object):
    def setupUi(self, sp):
        sp.setObjectName("sp")
        sp.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(sp)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(sp)
        self.label.setGeometry(QtCore.QRect(50, 122, 111, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(sp)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(sp)
        self.buttonBox.accepted.connect(sp.accept)
        self.buttonBox.rejected.connect(sp.reject)
        QtCore.QMetaObject.connectSlotsByName(sp)

    def retranslateUi(self, sp):
        _translate = QtCore.QCoreApplication.translate
        sp.setWindowTitle(_translate("sp", "Dialog"))
        self.label.setText(_translate("sp", "黑白噪声占比："))
