# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thresh_global.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_thresh_global(object):
    def setupUi(self, thresh_global):
        thresh_global.setObjectName("thresh_global")
        thresh_global.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(thresh_global)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(thresh_global)
        self.label.setGeometry(QtCore.QRect(60, 120, 91, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(thresh_global)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(thresh_global)
        self.buttonBox.accepted.connect(thresh_global.accept)
        self.buttonBox.rejected.connect(thresh_global.reject)
        QtCore.QMetaObject.connectSlotsByName(thresh_global)

    def retranslateUi(self, thresh_global):
        _translate = QtCore.QCoreApplication.translate
        thresh_global.setWindowTitle(_translate("thresh_global", "Dialog"))
        self.label.setText(_translate("thresh_global", "请输入阈值："))
