# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_translation(object):
    def setupUi(self, translation):
        translation.setObjectName("translation")
        translation.resize(400, 300)
        self.aaaa = QtWidgets.QDialogButtonBox(translation)
        self.aaaa.setGeometry(QtCore.QRect(-50, 230, 341, 32))
        self.aaaa.setOrientation(QtCore.Qt.Horizontal)
        self.aaaa.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.aaaa.setObjectName("aaaa")
        self.label = QtWidgets.QLabel(translation)
        self.label.setGeometry(QtCore.QRect(70, 70, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(translation)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(translation)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(translation)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 130, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(translation)
        self.aaaa.accepted.connect(translation.accept)
        self.aaaa.rejected.connect(translation.reject)
        QtCore.QMetaObject.connectSlotsByName(translation)

    def retranslateUi(self, translation):
        _translate = QtCore.QCoreApplication.translate
        translation.setWindowTitle(_translate("translation", "Dialog"))
        self.label.setText(_translate("translation", "dx："))
        self.label_2.setText(_translate("translation", "dy："))
